### ISSUE TITLE
Training Detail

### ISSUE THREAD

**Issue by yan-roo** [chilung/NCTU_Adv_DNN_HW3#1]
Great work!
Just want to ask in your Colab:
```
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
```
Are you using COCO pretrain model?

**Comment by chilung** [comment]
No. I retrained the model, although the code leave the original download model. The train start epoch 0 and I train the model till epoch 63999. And I upload the model I trained in my top mAP list: mAP 64.238% in epoch 48999, mAP 64.129% in epoch 41999, mAP 63.109% in epoch 33999, mAP 62.736% in epoch 61999, mAP 61.604% in epoch 56999, mAP 61.367% in epoch 52999 and mAP 60.899% in epoch 63999.

**Comment by chilung** [comment]
Should I delete the line of
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
And retrain the model again?

**Comment by chilung** [comment]
I comment out this line:
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
and restart my training from scratch in order to confirm my work.

**Comment by chilung** [comment]
@yan-roo I found that I indeed used COCO pre-trained model. After comment out the line of
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml")
It takes more epoch to converge. The training is still on going. I will update my new json and remove the old one.

**Comment by chilung** [comment]
I have removed my submission which pretrained model used. And upload new ones. It is obviously that the models trained from scratch are hard to get high score. And I continue training it to see if I can get higher score.
